site_name: TeachingHOW2s SSO
site_url: https://teachinghow2s.github.io/sso/

copyright: "&copy; Train Visual Ltd"

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
  favicon: images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: 'light-blue'
      accent: 'blue'
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: 'pink'
      accent: 'cyan'
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Overview: index.md
  - Configuration: configuration.md
  - User Provisioning: provisioning.md
  - Application Tiles: application-tiles.md
  - Identity Providers:
    - Azure: providers/azure.md
    - Google Apps: providers/google.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - smarty

extra:
  social:
    - icon: fontawesome/solid/house-chimney
      link: https://teachinghow2s.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/train-visual
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/teachinghow2s
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCYCt-D1t-YX_bAEPeAUxaBg/videos

extra_css:
  - assets/custom.css
